### ISSUE TITLE
Component development checklist

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#7]
This issue will serve as the checklist for developing different UI components and tracking the progress of each issue.

- [ ] Global `Web3Context`, connect wallet functionality and connect wallet UI
- [ ] ETH wallet address input with support for ENS domains
- [ ] Token amount/value input with easy conversion to-from wei<->ether

Will add more tasks soon.
