### ISSUE TITLE
Initialize the `@web3-ui/core` package

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#73]
As discussed in the Discord channel before, the `@web3-ui/core` package will be an opinionated package with an aim of providing *fully functional* UI components that work out-of-the-box. This package will be a combination of the `components` and `hooks` packages. 

Will post more details and a demo soon.

- [x] Add the `@web3-ui/core` package to the monorepo
- [x] Create a `ConnectWallet` component
- [ ] Create a small demo
